-- reset.sql
DROP TABLE IF EXISTS pagos_plataforma CASCADE;
DROP TABLE IF EXISTS compras CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS diseños CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;